name: Deploy Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.9

      - name: Install dependencies
        run: pnpm install

      - name: Build documentation
        run: |
          # Clean docs directory
          rm -rf docs
          # Generate documentation
          pnpm exec jsdoc -c jsdoc.config.js
          # Debug: Show directory structure
          echo "Documentation directory structure:"
          find docs -type f
          # Verify documentation was generated
          if [ ! -f "docs/jsdoc-experiment/1.0.0/index.html" ]; then
            echo "Error: Documentation was not generated correctly"
            ls -la docs/
            exit 1
          fi
          # Move files to the root of docs directory
          mv docs/jsdoc-experiment/1.0.0/* docs/
          rm -rf docs/jsdoc-experiment

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
